name: "Refresh Available Vanilla Versions"
on:
  # Manual trigger for just in case.
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: false
        default: 'main' # Uses the branch name that triggered the run
  schedule:
    # Set to run action once a day at 0:00 server time.
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow pushing to the repository for the action.
    steps:

      # Setup main as default branch if no other branch is supplied.
      - name: Use input or default branch
        run: |
          EVENT_NAME="${{ github.event_name }}"
          if [[ "$EVENT_NAME" = "workflow_dispatch" ]]; then
            echo "TARGET_BRANCH=${{ inputs.branch }}" >> $GITHUB_ENV
          else
            echo "TARGET_BRANCH=main" >> $GITHUB_ENV
          fi

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # Required for the action to be able to push
          fetch-depth: 0
          # This uses the specific ref (branch/tag/SHA) that the workflow was triggered on
          ref: ${{ env.TARGET_BRANCH }} 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Execute refresh script
        run: python scripts/refresh_vanilla_versions.py
          
      - name: Add any changed files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A

      - name: Commit changes if any
        run: |
          if git diff --cached --exit-code; then
            echo "No changes to commit. Skipping push."
            echo "PUSH_NEEDED=false" >> $GITHUB_ENV
          else
            git commit -m "Automated scheduled update"
            echo "Changes committed. Proceeding with push."
            echo "PUSH_NEEDED=true" >> $GITHUB_ENV
          fi
          
      - name: Push changes when change detected
        if: env.PUSH_NEEDED == 'true' # Check the environment variable
        run: git push
